'use strict';
let start = document.getElementById('start');
console.log(start);
let buttonPlus = document.getElementsByTagName('button'),
    buttonAddIncome = buttonPlus[0];
console.log(buttonAddIncome);
let buttonAddExpenses = buttonPlus[1];
console.log(buttonAddExpenses);
let additionalIncomeItem = document.querySelectorAll('.additional_income-item');
console.log(buttonAddExpenses);
let incomeItem = document.querySelectorAll('.income-items');
console.log(incomeItem);
let checkBoxDeposit = document.querySelector('#deposit-check');
console.log(checkBoxDeposit);
let inputResultBudgetMonth = document.getElementsByClassName('budget_month-value')[0];
console.log(inputResultBudgetMonth);
let inputResultBudgetDay = document.getElementsByClassName('budget_day-value')[0];
console.log(inputResultBudgetDay);
let inputResultExpensesMonth = document.getElementsByClassName('expenses_month-value')[0];
console.log(inputResultExpensesMonth);
let inputResultAdditionalIncome = document.getElementsByClassName('additional_income-value')[0];
console.log(inputResultAdditionalIncome);
let inputResultAdditionalExpenses = document.getElementsByClassName('additional_expenses-value')[0];
console.log(inputResultAdditionalExpenses);
let inputResultIncomePeriod = document.getElementsByClassName('income_period-value')[0];
console.log(inputResultIncomePeriod);
let inputResultTargetMonth = document.getElementsByClassName('target_month-value')[0];
console.log(inputResultTargetMonth);
let salaryAmount = document.querySelector('.salary-amount');
console.log(salaryAmount);
let incomeTitle = document.querySelector('input.income-title');
console.log(incomeTitle);
let incomeAmount = document.querySelector('input.income-amount');
console.log(incomeAmount);
let expensesTitle = document.querySelector('input.expenses-title');
console.log(expensesTitle);
let expensesItems = document.querySelectorAll('.expenses-items');
console.log(expensesItems);
let additionalExpensesItem = document.querySelector('.additional_expenses-item');
console.log(additionalExpensesItem);
let inputPeriodSelect = document.querySelector('.period-select');
console.log(inputPeriodSelect);
let periodAmount = document.querySelector('.period-amount');
console.log(periodAmount);
let targetAmount = document.querySelector('.target-amount');
console.log(targetAmount);